### ISSUE TITLE
TypeError: You provided 'undefined' where a stream was expected

### ISSUE THREAD

**Issue by thollander** [nestjs/cqrs#1015]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

3652ac1fb923443423dbe95c356b8470ce92d0e3

### Versions

8.0.3 -> 8.0.4

### Describe the regression

While bumping to the patch 8.0.4, my app starts to crash. 
I use CQRS combined with RxJS. 

```sh
[Nest] 66544  - 30/05/2022, 23:18:59   ERROR [EventBus] "SseRefreshLocalesDoneEventHandler" has thrown an error.
[Nest] 66544  - 30/05/2022, 23:18:59   ERROR [EventBus] TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
[Nest] 66544  - 30/05/2022, 23:18:59   ERROR [EventBus] "MetricsRefreshLocalesDoneEventHandler" has thrown an error.
[Nest] 66544  - 30/05/2022, 23:18:59   ERROR [EventBus] TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
[Nest] 66544  - 30/05/2022, 23:18:59   ERROR [EventBus] Command handler which execution was triggered by Saga has thrown an error.
```

```sh
[path]/node_modules/rxjs/src/internal/util/throwUnobservableError.ts:7
  return new TypeError(
         ^
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at Object.createInvalidObservableTypeError ([path]/node_modules/rxjs/src/internal/util/throwUnobservableError.ts:7:10)
    at Object.innerFrom ([path]/node_modules/rxjs/src/internal/observable/innerFrom.ts:40:9)
    at from ([path]/node_modules/rxjs/src/internal/observable/from.ts:103:52)
    at [path]/node_modules/@nestjs/cqrs/dist/event-bus.js:56:72
    at doInnerSub ([path]/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext ([path]/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next ([path]/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next ([path]/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at [path]/node_modules/rxjs/src/internal/operators/filter.ts:72:109
    at OperatorSubscriber._this._next ([path]/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
```

### Minimum reproduction code

```ts
import { IEventHandler, EventsHandler } from '@nestjs/cqrs';
import { RefreshLocalesDoneEvent } from '@nfs/features/translations/modules/cqrs';

import { TranslationsOperationsMetricsService } from '../translations-operations-metrics.service';

@EventsHandler(RefreshLocalesDoneEvent)
export class MetricsRefreshLocalesDoneEventHandler
  implements IEventHandler<RefreshLocalesDoneEvent>
{
  constructor(
    public operationsMetricsService: TranslationsOperationsMetricsService
  ) {}

  handle({ translationsDiff }: RefreshLocalesDoneEvent) {
    this.operationsMetricsService.injectMetrics(
      this.operationsMetricsService.aggregateOperationsMetrics(translationsDiff)
    );
  }
}
```

### Expected behavior

I should be able to use the patch version without my app to crash.

**Comment by kamilmysliwiec** [comment]
@Sikora00 this seems to be related to your commit

**Comment by luka-init** [comment]
@thollander had the same issue, for now returning `Promise.resolve()` seems to work
